### ISSUE TITLE
perf tool option is not working in the 2.4.0 release

### ISSUE THREAD

**Issue by pmereddy** [cloudera-labs/hive-sre#22]
Environment: CDP 7.1.7 kerberos and SSL enabled
hive-sre installed as non-root user, copied DB JDBC driver to $HOME/.hive-sre/aux_libs. sre and u3 worked. But, perf did not.

1. hive-sre perf tool did not accept --hadoop-classpath option
2. Without this option, I was getting "Driver not found" error

The attempt to copy the Hive JDBC driver to $HOME/.hive-sre/aux_libs did not work.

**Comment by dstreev** [comment]
Fixed classpath loading.  Removed --hadoop-classpath option which was displacing the jdbc jars.
