### ISSUE TITLE
Please create log folder in the respective sre-run output directory to avoid filling up install folder

### ISSUE THREAD

**Issue by mkempanna** [cloudera-labs/hive-sre#46]
Ask: Please create log folder in the respective sre-run output directory to avoid filling up install folder

Reason: Since root/home hive-sre installation folder is getting filled up very quickly with logs, subsequent runs fail in our automation flow with “out of disk space” error. Can the log folder for respective runs be created in respective output folders?

**Comment by dstreev** [comment]
Application Log output moved to Output directory.
