### ISSUE TITLE
Please add back the generation of managed_upgrade_2_acid.sql on top of the latest release 3.0.1.0

### ISSUE THREAD

**Issue by mkempanna** [cloudera-labs/hive-sre#49]
Ask: Please add back the generation of managed_upgrade_2_acid.sql on top of the latest release 3.0.1.0
Also, along with above, need “mysql_legacy_mngd_to_ext_purged.sql” and “mysql_missing_parts.sql” files to be generated as additional files.

Reason: We (The customer operations/platform team) want to continue sending sql commands directly (to convert managed to external) to our app teams who own respective DBs, so they still have an option of making the change themselves if they choose to (as in hive-sre version 2.x)

**Comment by dstreev** [comment]
Added back.
