### ISSUE TITLE
hive-sre script fails when encountering a non-hdfs scheme in the Hive location URI

### ISSUE THREAD

**Issue by maheshmpillai** [cloudera-labs/hive-sre#9]
The script failed with the following msg
` -count: java.net.URISyntaxException: Expected scheme-specific part at index 8: alluxio:`
The Hive path under question had the scheme alluxio:/warehouse...
Since it is a non-hdfs path, the `hdfs count` command fails. 

It would be nice if we could continue the run without failing and direct table details corresponding to the non-hdfs path to a separate report. In this way these could be reviewed separately.

**Comment by dstreev** [comment]
Can't recreate this in a manner that 'kills' hive-sre.
